### ISSUE TITLE
Last Login Not Updating

### ISSUE THREAD

**Issue by chrisandersonbtg** [UW-Madison-DoIT/jiraRemoteUserAuth#1]
Hello,

We are using this plugin for Jira version 6.2.7 and the Last Login information is not updating.  We have the following setting update.last.login.date=true in the remoteUserAuthenticator.properties.confluence.  We also use https://github.com/chauth/confluence_http_authenticator and he do not have that issue in Confluence with the same configuration.  I believe this use to work when we were on Jira 5.x, but I can't remember.  Are there any plans to support Jira 6.x and if so can you look into this issue?

Thanks,
Chris

**Comment by theseal** [comment]
Im about to upgrade our Jira v5.2.11 that uses this plugin. Last Login doesn't work in that old version either(wtih update.last.login.date=true). Not a big deal for us but still an issue.

**Comment by johnhare** [comment]
FYI: I just pushed up a new version with support for the update.last.login.date flag.
Seems to work for me on v6.4.
Haven't tested it on any other versions of Jira.

**Comment by chrisandersonbtg** [comment]
Hi John,

Thanks for this update.  It works great on 6.2.7 and 6.3.15.

Thanks,
Chris
